dada_core:
    resource: "@DadaCoreBundle/Resources/config/routing.yml"
    prefix:   /

dada_user:
    resource: "@DadaUserBundle/Resources/config/routing.xml"
    prefix:   "/account"

dada_advertisement:
    resource: "@DadaAdvertisementBundle/Resources/config/routing.yml"
    prefix:   "/advertisement"

dada_api:
    resource: "@DadaApiBundle/Resources/config/routing.xml"
    prefix:   "/api"

#FOSUserBunle routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#LiiPImagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#OAuth 2
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"