<?php

namespace Dada\ApiBundle\Repository;

/**
 * CacheTownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CacheTownRepository extends \Doctrine\ORM\EntityRepository
{
}
