<?php

namespace Dada\ApiBundle\Repository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return number of queries in last $minutes minutes
     *
     * @param $token string user token
     * @param $minutes integer number of minutes
     * @return mixed
     */
    public function countByMinutes($token, $minutes){
        $stringTime = 'PT'.$minutes.'M';
        $date = new \DateTime();
        $date->sub(new \DateInterval($stringTime));
        $current = new \DateTime();
        $query = $this->createQueryBuilder('a');
        $query->select('COUNT(a.id)')
            ->where('a.token = :token')
            ->andWhere('a.created BETWEEN :start AND :current')
            ->setParameter('token', $token)
            ->setParameter('start', $date)
            ->setParameter('current', $current);
        return $query->getQuery()->getSingleScalarResult();
    }
}
