<?php

namespace Dada\AdvertisementBundle\Repository;

/**
 * AdvertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementRepository extends \Doctrine\ORM\EntityRepository{

    /**
     * Retuns all items in the given page for the given user
     * @param $page int Page number
     * @param $user User User object
     * @param $nbItems int Nb items to show on a single page
     * @return array
     */
    public function findByPageAndUser($page, $user, $nbItems){

        $query = $this->createQueryBuilder('a')
            ->where('a.user = :user')
            ->setParameter('user', $user)
            ->setFirstResult((($page-1)*$nbItems))
            ->setMaxResults($nbItems)
            ->addOrderBy('a.public', 'desc')
            ->addOrderBy('a.published', 'asc');
        return $query->getQuery()->getResult();
    }

}
